apiVersion: v1
kind: Service
metadata:
  name: eed-software-postgres-pooler-rw
  namespace: eed-software-postgres
  annotations:
    metallb.universe.tf/address-pool: sdf-dmz
spec:
  type: LoadBalancer
  internalTrafficPolicy: Cluster
  ports:
  - name: pgbouncer
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/poolerName: eed-software-postgres-pooler-rw
