
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restore
  template:
    metadata:
      labels:
        app: restore
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        command:  [ "bash", "-c", "sleep infinity" ]

