
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:15.4
  instances: 3
  primaryUpdateStrategy: unsupervised
  # superuserSecret:
  #   name: postgresql-creds
  bootstrap:
    initdb:
      database: app-database 
      owner: postgresql
      secret:
        name: postgresql-creds
  # backup:
  #  retentionPolicy: "15d"
  #  barmanObjectStore:
  # destinationPath: "s3://[your-bucket-name]/[your-backup-folder]/"
  # endpointURL: "https://s3.hostname"
  #    s3Credentials:
  #      accessKeyId:
  #        name: s3-creds
  #        key: ACCESS_KEY_ID
  #      secretAccessKey:
  #        name: s3-creds
  #        key: ACCESS_SECRET_KEY
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: 'true'
  monitoring:
    enablePodMonitor: true
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  postgresql:
    parameters:
      log_disconnections: on
      log_duration: on
      log_min_duration_statement: 250ms
      log_statement: all
      log_temp_files: "1"
      maintenance_work_mem: 2GB
      max_connections: "1000"
      max_wal_size: 4GB
      min_wal_size: 2GB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      random_page_cost: "1.1"
      shared_buffers: 16GB
      work_mem: 160MB
  resources:
    requests:
      memory: 2Gi
      cpu: '1'
    limits:
      memory: 4Gi
      cpu: '2'
  storage:
    size: 10Gi


