apiVersion: v1
kind: Service
metadata:
  name: lb-postgres
  annotations:
    metallb.universe.tf/address-pool: sdf-services
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgresql
    role: primary